# Generated by Django 4.0.6 on 2022-08-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_created_userprofile_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allvotes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
