# Generated by Django 4.0.6 on 2022-08-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_allvotes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allvotes',
            name='votes',
            field=models.CharField(default='', max_length=100),
        ),
    ]
