# Generated by Django 4.0.6 on 2022-08-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_allvotes_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allvotes',
            name='votes',
            field=models.CharField(default='0 0 0 0 0 0 0 0 0 0 ', max_length=100),
        ),
    ]
