# Generated by Django 4.0.6 on 2022-08-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_allvotes_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created']},
        ),
    ]
